### ISSUE TITLE
Linksharing tests for current semantic behaviour

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#116]
### Goal

- As we begin to make performance improvements we want to ensure better test coverage so that we can better identify potential bugs when we change these code paths
- We need to validate that we have unique tests for each potential code path, so that this refactoring can be assured to not create new issues.  Some of this may exist in https://github.com/storj/gateway-mt/blob/main/testsuite/linksharing/handler_test.go.

### Acceptance Criteria

- Code paths identified
- Tests written for each code path

### Notes

 - See #54 for more context -- this is a prerequisite to being able to improve round trip performance

**Comment by halkyon** [comment]
A lot of this is already tested, but there's some gaps:

* Non-hosted prefix request with index.html cases
* Hosted requests: 404.html, index.html cases (e.g. requesting mydomain.com or mydomain.com/ would serve index.html)

I think I also discovered a bug where map `getLocations` fails for prefix request where an index.html resides at that prefix because it's trying to find the pieces for the prefix, not the index.html file.
