### ISSUE TITLE
Unable to register Access Grant with Auth Service

### ISSUE THREAD

**Issue by venomone** [storj/gateway-mt#169]
Hey folks,

I really liked the idea of the project, so I started implementing it myself with docker.
After everything seemed to be up and running fine, I'll try to register an Access Grant against the auth service like so:

uplink access register "super-secret-access-grant" --auth-service https://fqdn.my.domain → Domain is secured via Let's encrypt certificate.

But I'm only getting back:
```

uplink: dail to auth service failed: rpc: dial tcp 12.13.14.15:7777: connect: connection refused
	storj.io/uplink/edge.(*Config).RegisterAccess:64
	main.RegisterAccess:215
	main.(*cmdAccessRegister).Execute:50
	main.(*external).Wrap:123
	github.com/zeebo/clingy.(*Environment).dispatchDesc:126
	github.com/zeebo/clingy.(*Environment).dispatch:53
	github.com/zeebo/clingy.(*Environment).dispatchDesc:70
	github.com/zeebo/clingy.(*Environment).dispatch:53
	github.com/zeebo/clingy.Environment.Run:34
	main.main:25
	runtime.main:255
```
if I instead use --auth-service https://fqdn.my.domain:443 (with the port explicitly set) I get back the following:

```
uplink: register access for edge services failed: context canceled
	storj.io/uplink/edge.(*Config).RegisterAccess:83
	main.RegisterAccess:215
	main.(*cmdAccessRegister).Execute:50
	main.(*external).Wrap:123
	github.com/zeebo/clingy.(*Environment).dispatchDesc:126
	github.com/zeebo/clingy.(*Environment).dispatch:53
	github.com/zeebo/clingy.(*Environment).dispatchDesc:70
	github.com/zeebo/clingy.(*Environment).dispatch:53
	github.com/zeebo/clingy.Environment.Run:34
	main.main:25
	runtime.main:255
```

(12.13.14.15 is of course just a replacement for the real IP)

So do I also need to have at least one gateway-mt instance to make the registration process working? As to me, it seems that port 7777 indicated a gateway-mt instance.
Besides, is there any way I can tell uplink CLI to use a different port. Most of my mapping are on port 443 and not 7777 or 20000

Thanks in advance

**Comment by halkyon** [comment]
hi @venomone, you don't need Gateway-MT for registering access, only the authservice. The default is 7777 if no port is specified in the `--auth-service` flag which is the DRPC port of authservice in production (e.g. auth.us1.storjshare.io:7777).

Port 443 doesn't listen by default because there are multiple listeners on authservice. You can see flags and defaults by running authservice with `--help | grep listen` and specify these if you want to choose something different. If you're running authservice with a certificate, you should specify the DRPC+TLS port (default: 20003) when registering credentials e.g. `--auth-service fqdn.my.domain:20003`.

Admittedly there is a bit of a learning curve to running these services more than Gateway-ST, but it sounds like you're nearly there!

**Comment by venomone** [comment]
Thx for pointing this out! I wasn't aware what the DRPC port was used for.
