### ISSUE TITLE
badgerauth: Fuzzing of update logic

### ISSUE THREAD

**Issue by egonelbre** [storj/gateway-mt#178]
badgerauth needs to implement synchronization logic. One effective way to implement these is a fuzzing test.

The idea is to produce several operations from different nodes and then apply them in a random order (while preserving the on-node order). This should all result in the exact same database state.

**Comment by amwolff** [comment]
We removed invalidation and deletion from authservice, which drastically simplified synchronization logic. Because of this simplification, in a situation where we only have `CREATED` ops, implementing fuzzing for these would be a little overboard. Further testing will cover the synchronization in detail later on. I will close this issue for now, but if someone objects, feel free to reopen it.
