### ISSUE TITLE
Develop a test plan with the QA team to test badgerauth more extensively

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#193]
The new auth database might need some more exhaustive manual testing. It might be a good idea to test it in a real-world-style scenario:

1. bootstrapping of the cluster and migration,
2. adding and retrieving records,
3. teardown and addition of new nodes to the cluster,
4. corner case 1: trying to start a node with a different ID than in the database,
5. corner case 2: starting two nodes with the same ID,
6. corner case 3: ...

It might be a good idea to work with the QA team on this.

@storj/qa Will you have the bandwidth to work with us on this in the next sprint?

**Comment by littleskunk** [comment]
Some useful information:
Old design: https://storjlabs.atlassian.net/wiki/spaces/PM/pages/905445545/Design+Gateway+MT+Auth+service
New design: https://storjlabs.atlassian.net/wiki/spaces/PM/pages/2210529281/New+Authservice+Database

We should keep from the old design the security features.

**Comment by nadimhq** [comment]
New Auth Database blueprint: https://github.com/storj/gateway-mt/blob/main/docs/blueprints/new-auth-database.md
During implementation, we removed Invalidation and Deletion, so it's no longer there; it changes the design a little bit but only simplifies it
Package's README: https://github.com/storj/gateway-mt/tree/main/pkg/auth/badgerauth#readme
Unfortunately, as you can see, there isn't much here. We have these two issues to improve/write documentation: https://github.com/storj/gateway-mt/issues/191 & https://github.com/storj/gateway-mt/issues/194
I will focus on them in the sprint beginning tomorrow, so they should be resolved rather soon

**Comment by nadimhq** [comment]
<google-sheets-html-origin>

Test Scenario | Test Case | Description | Comments
-- | -- | -- | --
Latency | Read or Write Latency | If we have read or write latency it shouldn't be affected by cross-regional latency | **from design blueprint- latency range should be a couple of milliseconds
  | Replication Latency | If we have replication latency, then it should be configurable | **latency range should be a couple of seconds
ACID+ | Database Consistency | If we have an auth database, it should be consistent and shouldn't read stale data according to defined rules |  
  | Database Availability | Even if other authservices/regions are down, if we have any online authservice it should be able to respond to data from the DB |  
  | Database Isolation | If we have an auth database, then having multiple transactions in a database should not hinder it and should work as if they were executed one after the other | *from the design blueprint, Load- auth database doesn't do more than 1 request per second on average for both reads and writes however it can spike to 25 per second and is able to handle that
  | Database Durability 1 | If we have an auth database, then it should be durable and no external factors should hinder it | *from the design blueprint, we can ensure to never lose a record before it gets replicated to other nodes by having it write to two nodes synchronously as an example
  | Database Durability 2 | If we have two nodes synchronously written with the same record, then this should increase durability of writes to ensure we never lose a record before it gets replicated to other nodes | -if previously, mentioned durability change is used
  | Database Availability/Durability | Even if other authservices/regions are down, if we have any online authservice it should be able to respond to data from the DB |  
  | Database Atomicity | Records should be serialized, contain information such as (record data, denormalized information from access grant, sensitive data, invalid tracking, State and synchronization-related data) and saved in Protocol buffers binary format (any missing data should invalidate?) |  
  | Data Integrity | Records should be able to be added, retrieved, updated or deleted | **explained in KV interface implementation
Design | Generate Authservice ID | If we generate an ID for authservice at the start of an instance, then we should be able to avoid the case of human error (when someone puts up a cluster with the two same node IDs) |  
  | Alpha Implementation | At the start we should implement Put, Get, DeleteUnused and the replication mechanism |  
  | External Tool | For Deletion/invalidation/modification we should let that be handled by an external tool that connects to all nodes if needed |  
  | Unique ID 1 | Each node should have its own globally unique ID, test what happens with a node with a different ID than in the database |  
  | Unique ID 2 | Each node should have its own globally unique ID, test what happens if two nodes are trying to be started with the same ID |  
  | Replication Loop | Every node should run a replication loop, which should call replicate on all nodes that node knows in a fixed interval |  
  | Abusive Neighbor Node | Nodes can be abused since nodes can also return data for nodes that the node asking for data does not know about |  
  | Operations | Operations can be applied in any order to form the retrieval part of a local replica and should always result in a consistent view of the database |  
  | Modification | All modifications should be tied to node ID and all modifications of specific records should not be overwritten on other nodes, to maintain this records can only mutate from Created state to Invalidated/Deleted and from Invalidated to Deleted, this also means that it can never go back once a record is in a subsequent state |  
  | Garbage Collection | If a record is "deleted" it should transition to a deleted state and set with a time to live for the record (value), this value determines the time needed to pass for the data to then be garbage collected |  
  | Out of Sync Node Handling | When a responding node obtains counter values from its neighbors and it doesn't find a corresponding log entry (or the entry is too far in the past) it should respond with an out of sync error, and so the responding node should lock its read, writes, replication. After this, by syncing, the responding node should then create a new local replica and ask for data for all nodes it knows from counters = 0 and when the response no longer begins with the out of sync status code it will then unlock read, write, replication and go back to operating normally |  
  | Adding New Nodes to Cluster | Adding a new node to the cluster should just update the list of nodes it knows about and adding it to the list of nodes other nodes know about |  
  | Deleting Nodes from Cluster | Eventually, nodes will retire and these nodes should be deleted from the list of nodes other nodes know about so there won't be complications from being unable to connect to said retired node |  
  | Backups | Backups should be just local replicas compressed into Storj DCS after specified intervals |  
  | Migration | Migration could be triggered by a config flag, and as a background job it should move all data from CockroachDB to the new database, depending on the request (PUT- save record to new database) (GET- checks if new db contains the record and if not falls back to CockroachDB) |  
Implementation | Badger DB | BadgerDB should be used for the underlying key-value DB on every node |  
  | DRPC | DRPC should be used for replication-related communication |  
  | Record | Records should be serialized, contain information such as (record data, denormalized information from access grant, sensitive data, invalid tracking, State and synchronization-related data) and saved in Protocol buffers binary format |  
  | Replication Log Entry | With the replication log entry it can be key-only and may take this form- authservice_id/counter/encryption_key_hash/operation or it can also be a protobuff saved under authservice_id/counter |  
Key-Value Interface Implementation | Get | Get should retrieve record from KV store and then checks if it is valid and not in a temporary DELETED state, it returns nil if it doesn't exist and if its invalid it should explain in an error why |  
  | Put | Put should save record under encryption_key_hash and in addition create a corresponding replication log entry with the CREATED operation, if the key already exists then there should be an error for this case |  
  | Delete | Delete should in a series; retrieve a record, check if its already in a temporary DELETED state, modify the state to DELETED, create a log entry with DELETED operation, then after both the record and the replication log - entries should now have a set TTL (the time to live should be the same as after which offline nodes are out of sync and new TTL shouldn't be greater than already existing TTL). |  
  | DeleteUnused | Delete Unused deletes expired and invalid records from the KV store, meaning records that already come with an expiration date will have TTL set to that time and so will the nodes replicating these records along with their corresponding log entries |  
  | Invalidate | Invalidate should in a series, retrieve a record, then check whether the record is not already in an INVALIDATED/DELETED state, set it to INVALIDATE if it isn't, and finally create a corresponding replication log entry with the INVALIDATED operation |  
  | Ping | Ping attempts a DB roundtrip, but in the case of BadgerDB which would be embedded into the authservice it shouldn't be able to ping and thus this method should always return a nil error | *from design blueprint, can implement adding a test record and deleting it for Ping operation to ensure things work correctly
  | Close | Close should close the database and thus close the replication chore |  
Replication Chore Implementation | Replication Loop | Every node should run a replication loop, which means that all nodes should call Replicate on every node it knows in a fixed interval |  
  | Replicate Node | The node that calls replicate should gather the highest available counters for all nodes it knows about from its replication log and send them in the request |  
  | Responding Node | Nodes that receive a request from a node that calls replicate, should gather records and replication log entries above the counters from the request and send them in a batch that is configurable up to 10,000 records |  
  | Node Receiving the Batch | A node that receives said batch should add the received replication log entries and records to its local replica. Also records should be mutated with respect to the Design/Replication Algorithm f.e if the record entry has a TTL that should be added as well. Lastly, the created_at field should be updated asl well with the current time of the node receiving the response |  
  | Missed Log Entries | No log entries should be missed, since when a syncing node asks for entries it will look at the corresponding available records and if they don't match then the node will be out of sync |

**Comment by amwolff** [comment]
Thanks for writing this up!

I'm adding my thoughts on some points I feel need slight correction. Otherwise, it's great.

## ACID+

The new database is eventually consistent without configurable consistency constraints (you can't make it strongly consistent like you could Cassandra or DynamoDB), so not everything that falls under standard ACID compliance will apply here. Of course, the technology (BadgerDB) that powers local replicas is ACID-compliant but how they communicate is eventual consistency, so I prefer to say that the database is eventually consistent.

Two examples that might be useful:

1. If I insert a record to one authservice, the authservice responds with mapped credentials, crashes, and comes back up later—I should be able to retrieve that record using those credentials (local Durability from ACID).
2. If I insert a record to one authservice and try to retrieve it from another in the cluster immediately, it won't be instantly available (only after replication).

## Design

### External Tool

There's ongoing work making the auth-admin CLI tool: https://github.com/storj/gateway-mt/issues/190 (https://review.dev.storj.io/c/storj/gateway-mt/+/7675). It should be available soon. There's also https://dgraph.io/docs/badger/get-started/#installing-badger-command-line-tool (but it's much more low-level).

### Abusive Neighbor Node

This is a fantastic observation, and we also thought about it. Eventually, we decided to not make it impossible for nodes to explore the whole graph (see https://storj.slack.com/archives/C0196DNUML0/p1650974638284949).

### {Modification,Garbage Collection,Out of Sync Node Handling}

Since we don't have invalidation/deletion anymore, there will be no modification/out-of-sync node handling. However, there's still garbage collection for records inserted with TTL. But it's performed by BadgerDB (we use its native support for row-level TTL).

## Key-Value Interface Implementation

Likewise above, there's no invalidation/deletion, so some points might not apply anymore.

One more thing that I feel is important is that I have written exhaustive (I hope) documentation about the database. It's still in review (https://review.dev.storj.io/c/storj/gateway-mt/+/7669), but by rendering (might be easier to read this way) this Markdown and reading it, you will gain knowledge of how to start everything from the ground up.

**Comment by nadimhq** [comment]
Here are some security testing against Authservice cases (appreciate all feedback!) @amwolff <google-sheets-html-origin><!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}--

Authservice security testing |   |   |  
-- | -- | -- | --
Test Scenario | Test Case | Description | Comments
Security | Mutual Authentication | It should not be possible to start cluster without mutual authentication, have a test for trying to start a cluster without mutual authentication |  
  | Security Certificates- Generation | When generating the security certificates there should be a CA certificate, Server certificate and Key for server certificate |  
  | Security Certificates- Management | Certificates should be managed by a system and not a user (improving security) |  
  | Security Certificates- Rotation | Certificates should be rotated frequently for operational security; whether this is done manual or automated |  
  | Security Certificates- Expiration | Certificates should have an expiration, default 365 days, this is because one of the core features of SSLs is server authentication and as expirations carry validity periods they are used to establish secure connections |  
  | Directory (certs) | There should be a directory that contains CA and node certificates, also from this directory relevant files should be upload-able to nodes |  
  | Directory (safe-directory) | There should be a safe directory where CA keys can be stored safely (safe directory) and backed up, otherwise if its not stored safely and then gets compromised damage done can be substantial, and if lost it will be impossible to add new nodes to a cluster              The CA key should also never be uploaded to nodes, otherwise, it defeats the purpose of keeping it safe and secret | First layer of security for CA key
  | CA key (Multiperson Control) | There should be multiple objects required to activate and use CA private key, this will add another layer of security ((for example)as these multiple objects themselves can be separated and securely stored in a hardware security module or through locks and authentications) | Second layer of security for CA key
  | Network Security | Because it was decided to not make it impossible for nodes to ask for data it does not know about, there should be some kind of network policy or security to prevent rogue nodes from communicating with other nodes in a cluster or there could be a compromised cluster just because of one node that is affected |  
  | Cluster Differences | Misalignments in cluster nodes software shouldn't hinder security and or performance |  
  | Encryption | Data that is not contained in a safe directory should be encrypted for security purposes |  
  | Backups | Backups should be just local replicas compressed into Storj DCS after specified intervals | Moved from Design
Monitoring | Metrics | The new auth database should report metrics/events prefixed with 'as_badgerauth_' |  
  | Logs/Auditing 1 | There should be obtainable logs containing troubleshooting/helpful information at DEBUG level; f.e if there was a problem with a cluster, where did it occur, how/when did it happen, what was observed etc. | this can be implemented in the future since at the moment basic Info and metrics should be enough
  | Logs/Auditing 2 | If the above is implemented, then as a further improvement, there should be some type of Audit Policy where logs can be grouped in terms of severity(ignore or fix), priority, metadata info, requests etc. |  
  | Admin Tool | There should be an admin tool to query/monitor the badgerauth database (CLI tool) |  
  | Alerts | If there are any important logs that hint a problem/issue there should be an alert attached to it |

**Comment by ferristocrat** [comment]
AuthDB has been deployed to QA Environment: https://github.com/storj/infra/issues/2579 

cc @shaupt131

**Comment by amwolff** [comment]
The test plan is developed, so I'll be closing this issue.
