### ISSUE TITLE
Verify whether connection pooling (of DRPC connections) works correctly

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#201]
### Goal

Verify whether connection pooling works correctly both in Auth Service, Gateway-MT, and Link Sharing Service. We have concerns that connection pooling isn't correctly working because we do a lot of redials.

### Acceptance Criteria

We should answer the following questions:

- Why do we have a lot of redials with a connection pool?
- Is the connection pool "not working" (i.e., a lot of redials) only for
    - Auth Service (badgerauth), Gateway-MT, and Link Sharing Service,
    - or in general?
- How does the connection pool's size matter in the case of these services?

### Links

- The implementation we use: is https://pkg.go.dev/storj.io/common/rpc/rpcpool
- Artur already knows the answers to these questions, so he should write responses here

**Comment by ferristocrat** [comment]
Might be related to https://github.com/storj/gateway-mt/issues/252 @aishwaryasharmaccoew

**Comment by ferristocrat** [comment]
Might be related to https://github.com/storj/gateway-mt/issues/252 @aishwaryasharmaccoew

**Comment by aishwaryasharmaccoew** [comment]
Yes, This was one of the things I was exploring rn. Can pick up :)

**Comment by aishwaryasharmaccoew** [comment]
Checked the authservice register workflow but that dosent seem like the one we are looking for.
Tried to run the prod-like authservice cluster using a hetzner box, but Artur suggested a better way using docker-compose.
Not able to access the ports exposed on this cluster using localhost.
What would be the best way to debug this issue further?

**Comment by aishwaryasharmaccoew** [comment]
As discussed with Artur, the issue seems to be in the way the nodes communicate. 
When the system has at least three nodes, the communication channels form a clique with the nodes as the vertices and the connections as the edges.
During a process like replication, once the required object is found at one node the contexts to other nodes are closed, 
but this also evicts the connection to these other nodes from the pool, making them stale. This causes any new request to redial to these nodes. 
What we need to do to solve this issue is to terminate the requests to these other nodes while still maintaining them in the pool.
