### ISSUE TITLE
badgerauth: create Redash dashboard and alerts

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#206]
## Goal

Create a Redash dashboard and alerts with badgerauth's metrics.

## Acceptance Criteria

Dashboard and alerts are created with predefined metrics.

**Comment by halkyon** [comment]
I've set up some queries and alerts in redash, but there's a problem with redash in that it doesn't refresh queries on schedule, so alerts aren't being constantly evaluated to see if they need to fire. Rafael tracked it to a bug in redash, but it's still not solved yet. Personally I don't think it's a great tool for any kind of alerting capability because configuration options are very limited.

Could we use Chrongraf alerting instead? Authservice dashboard resides at https://chronograf.datasci.storj.io/sources/3/dashboards/128, but https://chronograf.datasci.storj.io/sources/3/alert-rules seems to indicate we need Kapacitor to enable alerts. Alternatively we could try using Thanos/Grafana?

**Comment by halkyon** [comment]
@amwolff any thoughts on this?

**Comment by amwolff** [comment]
@halkyon I feel like we came to the point where we finally need to think about moving to that Thanos/Grafana with all our stuff. Since Chronograf + Redash combo is limiting us and that Grafana instance seems well-maintained, we should probably go there. Maybe one thing to ensure is whether we need to make any backups of our dashboards and/or alerts. What do you think?

**Comment by halkyon** [comment]
@amwolff I agree with this. Should we close this issue and create a new one then? I guess this would be treated as new work and probably not for the current sprint?
