### ISSUE TITLE
Research how existing customers will be impacted/migrated to TLS custom domains

### ISSUE THREAD

**Issue by shaupt131** [storj/gateway-mt#234]
### Goal

-Research how existing customers **(secured and unsecured)** will be impacted/migrated to TLS secure custom domains.
-Will this break any existing customers using custom domains?  Specifically edge cases
-Can we make this conditional (opt-in)? (txt records)

### Acceptance Criteria

-A document detailing information pertaining to the above listed items, posted to ticket for review by the team
-Come up with a conditional mechanism for opt-in.  Add to document.  
-Two approvals from the team

### Links

 -

**Comment by pwilloughby** [comment]
### Changes in behavior
1. Currently https requests for custom domains return the default traefik self-signed cert.  After the migration a valid cert would be returned instead of the self-signed cert.
2. With https only mode enabled chrome shows a warning that the site doesn't support https and forces you to click through to the http page.  With TLS custom domains you would no longer see this warning.
### Edge cases
1. If a customer configured a proxy like cloudflare or fastly to use https and expect the self-signed cert serving a valid cert instead could cause an outage for them.
### Opt-in 
By adding an additional txt record with contents 'storj-tls' to the uplink dns configuration printout TLS could be opt-in.  I think opt-in is a good idea for the initial rollout to allow us to work out and issues with a small set of test customers.
`txt-www.beans.example.com	IN	TXT  	storj-tls`
Eventually TLS could be enabled by default and opt-in would become unnecessary.

**Comment by ferristocrat** [comment]
+1 on the opt in... that would solve for the edge case as well, since nothing would change with any existing configuration.

**Comment by amwolff** [comment]
Looks good to me.

**Comment by shaupt131** [comment]
Think we're set here then.  Moving to done status.  Thanks!
