### ISSUE TITLE
Retain the content and/or hash of linksharing files that we take down

### ISSUE THREAD

**Issue by ferristocrat** [storj/gateway-mt#343]
### Goal

- We want to start retaining the content and/or hash of linksharing files that we take down
- This will help us backtest any solution we may implement for proactively identifying these files (rather than waiting for a takedown request)

### Acceptance Criteria

- Manual or automated process implemented for storing the content and hash for files we take down

### Links

 - N/A

**Comment by amwolff** [comment]
Any idea where we should store it?

**Comment by amwolff** [comment]
I think we should use eventkit for this.

**Comment by amwolff** [comment]
From sprint planning: probably implement the functionality in authservice-admin to send a hash of the object to eventkit for later analysis.

v2 would be moving the offending object to a bucket that we control while scanning it beforehand with, e.g., ClamAV—if the object is malware/dangerous, we would keep it and discard otherwise.

**Comment by amwolff** [comment]
@jtolio Related to #342, how do you feel about retaining the checksum of the content that we take down for legal reasons?
