### ISSUE TITLE
More client side caching / less downloading of previews in Satellite UI

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#59]
Steps to reproduce:

All the steps must be done from UI.
    PS: Having the dashboard section in a separated tab will help to compile the information.
    Check the current bandwidth usage before starting
    Upload a .MP4 file to a bucket
    Right after the file is uploaded (preview screen) check the bandwidth again.
    Click on linksharing
    Check the bandwidth again

Gateway-MT seems to have Cache-Control, Last-Modified, and ETag headers, linksharing does not.
Somehow it seems like we get Last-Modified headers anyway (Traefik?).

Moby says the only the Object Browser that appears to handle caching poorly.

**Comment by halkyon** [comment]
So each time you open a preview it creates a new presigned URL signature etc in query values. It seems the issue is the access  credential remains the same, but the date has changed, therefore varying the signature to bust the cache.

Here's an example of the first preview generated:

```https://gateway.us1.storjshare.io/testfiles/Sample-MP4-Video-File-for-Testing.mp4
?X-Amz-Algorithm=AWS4-HMAC-SHA256
&X-Amz-Credential=jxvwuolkj2bga7vg5jf3xsoodxvq%2F20211013%2Fus-east-1%2Fs3%2Faws4_request
&X-Amz-Date=20211013T001117Z
&X-Amz-Expires=900
&X-Amz-Signature=d68ca473b40631f88f149a60bada365e2ffb4c7173fc0741c71715a770355f02
&X-Amz-SignedHeaders=host```

And here's the second after re-opening the dialog:

```https://gateway.us1.storjshare.io/testfiles/Sample-MP4-Video-File-for-Testing.mp4
?X-Amz-Algorithm=AWS4-HMAC-SHA256
&X-Amz-Credential=jxvwuolkj2bga7vg5jf3xsoodxvq%2F20211013%2Fus-east-1%2Fs3%2Faws4_request
&X-Amz-Date=20211013T001335Z
&X-Amz-Expires=900
&X-Amz-Signature=9543a9b2191c2e818a2cd1000b993108a2778c5fcd42f04936d798bf92e71aab
&X-Amz-SignedHeaders=host```

It seems some others have run across this problem: https://advancedweb.hu/cacheable-s3-signed-urls/

@mobyvb Any more thoughts to add here? Am I on the right track?

**Comment by halkyon** [comment]
I had a go trying to patch the browser to support this, but I have no idea what I'm doing :D https://gist.github.com/halkyon/f0e07e938e5ec3210385c93eb4058891. It seems clear I haven't got a proper local development environment ready to test this. Could someone else please pick this up while I'm away the next few days?
